name: Deploy GitHub Pages

# 触发条件：推送到 main 分支就自动执行
on:
  push:
    branches: [ main ]

# 允许部署pages权限
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制：避免多次部署冲突
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ①拉取代码
      - name: Checkout source
        uses: actions/checkout@v4

      # ②配置node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # ③安装依赖 & build
      - name: Configure npm registry
        run: |
          npm config set registry https://registry.npmmirror.com
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # ④上传构建产物dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # ⑤部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
